version: "3.8"

services:
  backend: 
    depends_on: 
      - db
    build: .
    ports: 
      - 3001:3001

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
