name: Deploy backend

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build & test
        run: |
          docker-compose up
          npm run test
          
